# This is a basic workflow to help you get started with Actions

name: vagrant-up

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  vagrant-up:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Show Vagrant version
        run: vagrant --version

      - name: Create virtualbox hostonly network
        run: VBoxManage hostonlyif create && VBoxManage hostonlyif ipconfig vboxnet0 --ip 172.28.128.1

      - name: Run vagrant up
        run: vagrant up

      - name: ssh into box after boot
        run: vagrant ssh cordra_nsidr_server -c "echo 'hello world!' && echo hostname -I "
